# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"
  
[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[dev]
autoLaunch = false
command = "npm run dev"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"